### ISSUE TITLE
The path to the game's di rectory is incorrect.

### ISSUE THREAD

**Issue by KUKLY** [joelamos/SourceRadio#10] opened 2017-01-02 22:15 UTC
**** SourceRadio v2016.08.03 ****

Enter the game you're playing. (Options: tf2, csgo, l4d2)
csgo
Exception in thread "main" java.lang.RuntimeException: The path to the game's directory is incorrect.
        at com.joelchristophel.sourceradio.ScriptWriter.writeScripts(ScriptWriter.java:39)
        at com.joelchristophel.sourceradio.Playlist.initialize(Playlist.java:157)
        at com.joelchristophel.sourceradio.Playlist.<init>(Playlist.java:143)
        at com.joelchristophel.sourceradio.Playlist.getInstance(Playlist.java:124)
        at com.joelchristophel.sourceradio.Playlist.main(Playlist.java:93)
C:\Program Files (x86)\SourceRadio>cmd /k
C:\Program Files (x86)\SourceRadio>

steam path -> D:\Program Files (x86)\Steam

**Comment by joelamos** [comment] 2017-01-05 02:19
Duplicate of #9

**Closed by joelamos** 2017-01-05 02:19 UTC
Labels: duplicate
